apiVersion: v1
kind: Pod
metadata:
  name: kristojeremy-pod
spec:
  restartPolicy: Always # Ensures the pod restarts if it crashes
  volumes:
    - name: kristojeremy-pv-storage
      persistentVolumeClaim:
        claimName: rizkifauzan-pv-claim
  containers:
    - name: kristojeremy-container
      image: "nvcr.io/nvidia/pytorch:24.11-py3" # Use a suitable image
      command: ["/bin/sh"]
      args: [
          "-c",
          "while true; do echo 'kristojeremy-pod is running'; sleep 10; done",
        ] # Keep the container alive
      volumeMounts:
        - mountPath: "/workspace"
          name: kristojeremy-pv-storage
